name = "test_rp2040_hal"
description = "Unit tests for rp2040_hal"
version = "2.3.0"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]

executables = ["test_rp2040_hal"]

[[depends-on]]  # Added by alr
rp2040_hal = "^3"
aunit = "^24"
gnatcov = "^22"
embedded_rp2350 = ">=15"

[[pins]]
rp2040_hal = { path='..' }

[gpr-set-externals]
AUNIT_RUNTIME = "ravenscar"
EMBEDDED_RP2350_BUILD = "Debug"

[build-profiles]
"*" = "development"
cortex_m = "release"
usb_embedded = "release"
atomic = "release"
aunit = "development"

[configuration.values]
rp2040_hal.Device = "RP2350A"
embedded_rp2350.Board = "rpi_pico2"
