name = "rp2040_hal"
description = "Drivers and HAL for the RP2040 micro-controller family"
version = "3.0.0-alpha1"
licenses = "BSD-3-Clause"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
tags = ["embedded", "nostd", "rp2040", "raspberrypi", "drivers"]
website = "https://pico-doc.synack.me/"

[[depends-on]]
cortex_m = "^1"
atomic = "^1"
hal = "^1"
usb_embedded = "^1"

[configuration.values]
atomic.Backend = "armv6m"
cortex_m.core = "m0p"

[configuration.variables]
Device = {type = "Enum", values = [
    "RP2040",  # Cortex-M0+, QFN-56, 30 GPIO, no internal flash
    "RP2350A", # Cortex-M33, QFN-60, 30 GPIO, no internal flash
    "RP2354A", # Cortex-M33, QFN-60, 30 GPIO, 2 MB internal flash
    "RP2350B", # Cortex-M33, QFN-80, 48 GPIO, no internal flash
    "RP2354B", # Cortex-M33, QFN-80, 48 GPIO, 2 MB internal flash
], default = "RP2040"}
