name = "rp2040_hal"
description = "Drivers and HAL for the RP2040 micro-controller family"
version = "0.7.0"
licenses = "BSD-3-Clause"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
tags = ["embedded", "nostd", "rp2040", "raspberrypi", "drivers"]
website = "https://github.com/JeremyGrosser/rp2040_hal"

[[depends-on]]
cortex_m = "~0.3"
hal = "~0.1"

[[depends-on]]
usb_embedded = "~0.1.0"
gnat_arm_elf = "^11.2.2"

[[pins]]
atomic = { url='https://github.com/Fabien-Chouteau/atomic#critical_sections' }
bbqueue = { url='https://github.com/Fabien-Chouteau/bbqueue-spark' }
usb_embedded = { url='https://github.com/Fabien-Chouteau/usb_embedded' }

[configuration.variables]
Flash_Chip = {type = "Enum",  values = ["w25qxx", "generic_qspi", "generic_03"], default = "w25qxx"}

[configuration.values]
atomic.Backend = "armv6m"
