name = "rp2040_hal"
description = "Drivers and HAL for the RP2040 micro-controller family"
version = "2.4.0"
licenses = "BSD-3-Clause"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
tags = ["embedded", "nostd", "rp2040", "raspberrypi", "drivers"]
website = "https://pico-doc.synack.me/"

[[depends-on]]
cortex_m = "^1"
atomic = "^1"
hal = "^1"
usb_embedded = "^1"
gnat_arm_elf = "^14"

[configuration.variables]
Device = {type = "Enum", values = ["rp2040", "rp2350"], default = "rp2040"}
Flash_Chip = {type = "Enum",  values = ["w25q080", "generic_qspi", "generic_03"], default = "w25q080"}
Interrupts = {type = "Enum",  values = ["hal", "bb_runtimes"], default = "hal"}
Use_Startup = {type = "Boolean", default = true}

[configuration.values]
atomic.Backend = "armv6m"
cortex_m.core = "m0p"
