--
--  Copyright (C) 2022 Jeremy Grosser <jeremy@synack.me>
--
--  SPDX-License-Identifier: BSD-3-Clause
--
--------------------------------------------------------
-- This file is autogenerated by pioasm; do not edit! --
--------------------------------------------------------

pragma Style_Checks (Off);

package RP.PIO.WS2812_PIO
   with Preelaborate
is
   ------------
   -- Ws2812 --
   ------------

   Ws2812_Wrap_Target : constant := 0;
   Ws2812_Wrap        : constant := 3;

   T1 : constant := 2;
   T2 : constant := 5;
   T3 : constant := 3;

   Ws2812_Program_Instructions : RP.PIO.Program := (
                    --  .wrap_target
         16#6221#,  --   0: out    x, 1            side 0 [2]
         16#1123#,  --   1: jmp    !x, 3           side 1 [1]
         16#1400#,  --   2: jmp    0               side 1 [4]
         16#a442#); --   3: nop                    side 0 [4]
                    --  .wrap

end RP.PIO.WS2812_PIO;
