#!/bin/sh

TRIPLE=riscv64-unknown-elf
CC=${TRIPLE}-gcc
WORKDIR=${PWD}
STARTUP_DIR=${WORKDIR}/../src/startup/rp2350
PICO_SDK_PATH=pico-sdk
if [ ! -e ${PICO_SDK_PATH} ]; then
    git clone --branch=develop --depth=1 https://github.com/raspberrypi/pico-sdk ${PICO_SDK_PATH}
fi
cd ${PICO_SDK_PATH}/src

prep_boot2() {
    ${CC} -E \
        -I${WORKDIR}/include \
        -Icommon/pico_base_headers/include \
        -Irp2_common/pico_platform_compiler/include \
        -Irp2_common/pico_platform_panic/include \
        -Irp2_common/pico_platform_sections/include \
        -Irp2_common/hardware_hazard3/include \
        -Irp2350/pico_platform/include \
        -Irp2350/hardware_regs/include \
        -Irp2350/hardware_structs/include \
        -Irp2350/boot_stage2/asminclude \
        rp2350/boot_stage2/boot2_$1.S >${WORKDIR}/../boot2/generated/boot2__rp2350_$1.S
    echo "$1"
}

prep_crt0() {
    if [ ! -d ${STARTUP_DIR} ]; then
        mkdir -p ${STARTUP_DIR}
    fi

    ${CC} -E \
        -I${WORKDIR}/include \
        -Icommon/pico_base_headers/include \
        -Icommon/pico_binary_info/include \
        -Icommon/boot_picobin_headers/include \
        -Irp2_common/pico_platform_compiler/include \
        -Irp2_common/pico_platform_panic/include \
        -Irp2_common/pico_platform_sections/include \
        -Irp2_common/boot_bootrom_headers/include \
        -Irp2_common/pico_bootrom/include \
        -Irp2_common/hardware_hazard3/include \
        -Irp2350/pico_platform/include \
        -Irp2350/hardware_regs/include \
        -Irp2350/hardware_structs/include \
        rp2_common/pico_crt0/crt0_riscv.S >${STARTUP_DIR}/crt0_riscv.S
    echo "crt0_riscv"
}

prep_boot2 generic_03h
prep_boot2 w25q080

prep_crt0
