#!/bin/sh
# This script assembles a pio file into binary then converts it into an elf
asm_name=$1
name=$(echo "$(basename ${asm_name})" | cut -f1 -d'.')
bin_name="${name}.bin"
elf_name=$2

pioasm -o binary $asm_name $bin_name && 
arm-eabi-objcopy \
    -I binary \
    -O elf32-littlearm \
    -B armv6s-m \
    --redefine-sym=_binary_${name}_bin_start=${name}_pio_start \
    --redefine-sym=_binary_${name}_bin_end=${name}_pio_end \
    --redefine-sym=_binary_${name}_bin_size=${name}_pio_size \
    ${bin_name} \
    ${elf_name}
