name: Build with Alire
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          toolchain: gnat_arm_elf gprbuild
      - uses: alire-project/setup-alire@v1
      - run: alr build
