name: Build with Alire
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: alire-project/setup-alire@v5
        with:
          version: nightly
      - name: Build tests (master)
        if: github.ref != 'refs/heads/3.x'
        run: cd tests; alr build
      - name: Build tests_rp2040 (3.x)
        if: github.ref == 'refs/heads/3.x'
        run: cd tests_rp2040; alr build
      - name: Build tests_rp2350 (3.x)
        if: github.ref == 'refs/heads/3.x'
        run: cd tests_rp2350; alr build
